"""add has_shop to seller

Revision ID: 2fe6e4596e17
Revises: 3869e5f51f72
Create Date: 2024-12-22 01:51:39.378480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe6e4596e17'
down_revision = '3869e5f51f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_shop', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('has_shop')

    # ### end Alembic commands ###
